[package]
name = "quick-sequence-code"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.105"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"

[build]
target = "wasm32-unknown-unknown"
