[package]
name = "qsc-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
